Exception in thread "main" java.lang.NullPointerException
	at semper.sil.ast.utility.Consistency$.isAssignable(Consistency.scala:41)
	at semper.sil.ast.utility.Consistency$$anonfun$areAssignable$1.apply(Consistency.scala:45)
	at semper.sil.ast.utility.Consistency$$anonfun$areAssignable$1.apply(Consistency.scala:45)
	at scala.collection.LinearSeqOptimized$class.forall(LinearSeqOptimized.scala:69)
	at scala.collection.immutable.List.forall(List.scala:78)
	at semper.sil.ast.utility.Consistency$.areAssignable(Consistency.scala:45)
	at semper.sil.ast.Call$class.$init$(Statement.scala:62)
	at semper.sil.ast.DomainBinExp.<init>(Expression.scala:568)
	at semper.sil.ast.Add.<init>(Expression.scala:37)
	at semper.chalice2sil.translation.ProgramTranslator.translateExp(ProgramTranslator.scala:377)
	at semper.chalice2sil.translation.ProgramTranslator.translateExp(ProgramTranslator.scala:359)
	at semper.chalice2sil.translation.ProgramTranslator$$anonfun$translate$4.apply(ProgramTranslator.scala:211)
	at semper.chalice2sil.translation.ProgramTranslator$$anonfun$translate$4.apply(ProgramTranslator.scala:204)
	at scala.collection.immutable.List.foreach(List.scala:309)
	at semper.chalice2sil.translation.ProgramTranslator.translate(ProgramTranslator.scala:204)
	at semper.chalice2sil.translation.ProgramTranslator.translate(ProgramTranslator.scala:184)
	at semper.chalice2sil.translation.ProgramTranslator$$anonfun$translate$2.apply(ProgramTranslator.scala:75)
	at semper.chalice2sil.translation.ProgramTranslator$$anonfun$translate$2.apply(ProgramTranslator.scala:75)
	at scala.collection.immutable.List.foreach(List.scala:309)
	at semper.chalice2sil.translation.ProgramTranslator.translate(ProgramTranslator.scala:75)
	at semper.chalice2sil.Program$.main(Program.scala:94)
	at semper.chalice2sil.Program.main(Program.scala)
